;; ==========================================================
;; CHALLENGE 13: Reverse-Until (Partial Reverse)
;; ----------------------------------------------------------
;; TASK:
;; Write 'reverse-Until' that takes a list $list and an index
;; $n. Reverse the elements from index 0 to index N, and keep
;; the rest of the list unchanged.
;;
;; SIGNATURE:
;; (= (reverse-Until $list $n) ( ... ))
;;
;; TEST CASE:
;; !(reverse-Until (A B C D E) 2) ; Should return (C B A D E)
