;; ==========================================================
;; CHALLENGE 9: The "Totalizer" (Folding)
;; ----------------------------------------------------------
;; TASK: Given a shopping cart as list of prices: (10.5 5.0 25.99)
;;  1. Use the fold function to calculate all prices in the cart.
;;  2. Find the maximun price using fold and a combiner function.
;; GOAL: 
;; Understand how to collapse a list into a single, meaningful value.
